name: Publish
on:
  push:
    branches:
      - master
    paths:
      - model/**
      - src/**
      - submodules/**
      - test/**
      - VERSION.txt

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: "*"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish demo place
        run: |
          rokit --version
          rojo --version
          rojo upload --api_key "${{ secrets.PLACE_PUBLISHING_KEY }}" --universe_id ${{ secrets.TEST_UNIVERSE_ID }} --asset_id ${{ secrets.TEST_PLACE_ID }} test
